language: node_js
node_js:
  - "8.9.1"
script:
  - yarn clear
  - npm version patch
  - npm publish
branches:
  only:
    - master
deploy:
  provider: npm
  email: $USER_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true